### PR TITLE
Vision Document Template - updated

### PR DESCRIPTION
**Pull request by Nijaoui-Wassim**
(2): Positioning: Zachary Bruce
(3): Stakeholder description: Louisa-Lina Meziane, Haris Mahmood
(4): Product overview: Zayneb Mehdi, Carson Senthilkumar
(5): Product features: Victoria Castelli, Khaled Owaida
(6): Risk & feasibility: Wassim Nijaoui
(7): use case: Ziyi Wang, Jiayi Chen

### CODE REVIEW

**Comment by Nijaoui-Wassim** [comment]
Hey guys, I just updated q6, thanks for verifying and making sure everything is good, thanks

**Comment by louisa-lina** [comment]
For section 3 , everything looks good :)

**Comment by VCastelli** [comment]
Thanks for creating the pull request. 

The Use Case Diagram and the Key Stakeholder or User Needs sections turned out really well! 

Everything looks good to me in the document. :)

**Review by z-bruce — APPROVED** [review]
Everything looks good!

**Review by BrainOverfl0w — APPROVED** [review]
Thanks for the update ! Everything looks good

**Comment by JIAYI615** [comment]
good job! Everything looks good

**Comment by KhaledOwaida** [comment]
Risk and Feasibility section loos good! Great work everyone

**Comment by Zeebruh326** [comment]
Everything looks just fine, well done everyone!

**Comment by haris2055** [comment]
Everything looks good, great work!

**Review by haris2055 — APPROVED** [review]

**Comment by CarsonSSk** [comment]
Hey I have reviewed the commit, everything looks good. Thanks!

**Pull request merged**
