### PR TITLE
Vision Document Template

### PR DESCRIPTION
**Pull request by haris2055**
(2): Positioning: Zachary Bruce
(3): Stakeholder description: Louisa-Lina Meziane, Haris Mahmood 
(4): Product overview: Zayneb Mehdi, Carson Senthilkumar 
(5): Product features: Victoria Castelli, Khaled Owaida
(6): Risk & feasibility: Wassim Nijaoui 
(7): use case: Ziyi Wang, Jiayi Chen

### CODE REVIEW

**Review by BrainOverfl0w — APPROVED** [review]
Looks great. Good work everyone !

**Review by JIAYI615 — APPROVED** [review]
good job guys!

**Comment by Nijaoui-Wassim** [comment]
Great work everyone !

**Comment by KhaledOwaida** [comment]
Everything looks fine!

**Pull request merged**
